CREATE OR REPLACE STAGE STM.ADM.STUDENT_DATA_STAGE;

-- 110,Meera Joshi,10,Science,87

CREATE OR REPLACE TABLE STM.ADM.STUDENTS (
    ROLL_NUMBER STRING,
    NAME STRING,
    CLASS STRING,
    SUBJECT STRING,
    MARKS NUMBER
);

CREATE OR REPLACE FILE FORMAT STM.ADM.STUDENTS_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE PIPE STM.ADM.STUDENTS_PIPE
AS
COPY INTO STM.ADM.STUDENTS
FROM @STM.ADM.STUDENT_DATA_STAGE
FILE_FORMAT = (FORMAT_NAME = STM.ADM.STUDENTS_CSV_FORMAT);

-- COPY INTO STM.ADM.STUDENTS
-- FROM @STM.ADM.STUDENT_DATA_STAGE
-- FILE_FORMAT = (FORMAT_NAME = STM.ADM.STUDENTS_CSV_FORMAT)
-- ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE STM.ADM.STUDENTS_PIPE
AS
COPY INTO STM.ADM.STUDENTS
FROM @STM.ADM.STUDENT_DATA_STAGE
FILE_FORMAT = (FORMAT_NAME = STM.ADM.STUDENTS_CSV_FORMAT);

ALTER PIPE STM.ADM.STUDENTS_PIPE REFRESH;
