CREATE DATABASE STM ;
CREATE SCHEMA ADM ;

CREATE OR REPLACE TABLE STM.ADM.USERS (
    USER_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

SELECT * FROM STM.ADM.USERS;

