CREATE DATABASE STM ;
CREATE SCHEMA ADM ;

CREATE OR REPLACE TABLE STM.ADM.USERS (
    USER_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    PASS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

CREATE OR REPLACE MASKING POLICY PASSWORD_MASK AS
(val STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN')
        THEN val
    ELSE '********'
END;

ALTER TABLE STM.ADM.USERS
MODIFY COLUMN PASS
SET MASKING POLICY PASSWORD_MASK;

SELECT * FROM STM.ADM.USERS;

