CREATE OR REPLACE STAGE STM.ADM.STUDENT_CSV_STAGE;


CREATE  OR REPLACE TABLE STM.ADM.STUDENT_CSV (
    ID INT,
    NAME VARCHAR(100),
    DATE DATE,
    TELUGU INT,
    ENGLISH INT,
    SCIENCE INT,
    MATH INT,
    SOCIAL INT
);

CREATE OR REPLACE FILE FORMAT STM.ADM.STUDENT_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_DELIMITER=',';


CREATE OR REPLACE PIPE STM.ADM.STUDENTS_CSV_PIPE
AS
COPY INTO STM.ADM.STUDENT_CSV
FROM @STM.ADM.STUDENT_CSV_STAGE
FILE_FORMAT = (FORMAT_NAME = STM.ADM.STUDENT_CSV_FORMAT);



ALTER PIPE STM.ADM.STUDENTS_CSV_PIPE REFRESH;

list @STM.ADM.STUDENT_CSV_STAGE;

select * from STM.ADM.STUDENT_CSV;
